### ISSUE TITLE
train time

### ISSUE THREAD

**Issue by syjxxxx** [wjun0830/Difficulty-Aware-Simulator#1]
训练多少epoch，200 epoch结束还有，要等多久呢？

**Comment by wjun0830** [comment]
Thank you for your interest in our work.

We train the model for 200 epochs and the training time depends on the size of the dataset.
Tiny-ImageNet and CIFAR10+ datasets take a relatively shorter time.
If you want to train the model more fastly, you can use 
```
from torch.cuda.amp import autocast
from torch.cuda.amp import GradScaler
```

Since I do not speak Chinese, I hope this answers your question.

**Comment by syjxxxx** [comment]
"==> Epoch 196/200
==> Epoch 197/200
==> Epoch 198/200
==> Epoch 199/200
==> Epoch 200/200
Acc: 95.93333
cifar10 Preparation
Selected Labels:  [7, 1, 0, 9, 4, 6]
Files already downloaded and verified
All Train Data: 50000
Files already downloaded and verified
All Test Data: 10000
Files already downloaded and verified
Train:  30000 Test:  6000 Out:  4000
All Test:  10000
==> Epoch 1/200
==> Epoch 2/200
==> Epoch 3/200
==> Epoch 4/200
==> Epoch 5/200"
This is the output file of my training. After training for 200 epochs, there is only accuracy. And then training next 200 epochs.

**Comment by wjun0830** [comment]
Have you created logs directory? If you check the line 352 in osr.py, it creates logs in the logs directory.
Make sure you have created the logs directory before you actually run the code.

**Comment by syjxxxx** [comment]
I use background run by "nohup python -u osr.py > log 2>&1 &"
When running the code, line 355 reported an error, and I modified it according to line 352 to“     if options['dataset'] == 'cifar100':
            stats_log = open('./logs/' + options['split'] + '/' + options['dataset'] + '/DIAS_%d' % (i) + str(options[
                'out_num']) + '.txt', 'w')
        else:
            stats_log = open('./logs/' + options['split'] + '/' + options['dataset'] + '/DIAS_%d' % (i) + str(options['out_num']) + '.txt', 'w')”

**Comment by wjun0830** [comment]
Can you show me the error message?

**Comment by syjxxxx** [comment]
Sorry,I can't find it.
I find the running result of the code. Is it in the /logs/F1/cifar10/DIAS_050.txt

**Comment by wjun0830** [comment]
Yes, that is the one of the result with F1 split protocol.
