### ISSUE TITLE
Question about ARPL results in paper

### ISSUE THREAD

**Issue by Hrren** [wjun0830/Difficulty-Aware-Simulator#2]
Hello
Thanks for your wonderful job,  but I have a question:
Why the result in paper about ARPL is  much lower  than that in original ARPL paper.
![image](https://user-images.githubusercontent.com/88883209/191187564-8395e999-be65-4577-a1db-50201b8a4212.png)
![image](https://user-images.githubusercontent.com/88883209/191187628-1ddc865d-8a92-43e5-87eb-55baa1316e72.png)
Noticed that the data split is different, but these two results differs illogically a lot, 
I want to know how do you reproduce the ARPL result in paper? 
Do you reproduce it follow the ARPL optimizer and training setting or follow your setting in paper?
I have reproduce the ARPL, it is the same in ARPL paper, so it really confused me.

**Comment by wjun0830** [comment]
Thanks for your interest.

As you mentioned, the performance gap only comes from the different split information.
We used the ARPL's official GitHub implementation to reproduce the performance.

So, if you try to run with our publicized split information, you may get the same results in our table.

The reason why the performance gap is noticeable is that the split information is critical in the literature on open set recognition.

Suppose you have open set classes that one is very similar to a closed set class and the other not.
Then, we can expect the classifier to easily distinguish the latter open set class while the former is hard to be distinguished.
For these reasons, in the paper, we argued that the split information should be unified to fairly measure the performance between methods.
