### ISSUE TITLE
Question about Inherent threshold calculation

### ISSUE THREAD

**Issue by ZhongQiuyuan** [wjun0830/Difficulty-Aware-Simulator#3]
Thanks for your work.

According to the formula for calculating the threshold in the paper
![image](https://user-images.githubusercontent.com/55440897/203790504-e4909077-d45a-4581-827b-a4a24f6a1e8b.png)
and and the corresponding code
`thr = options['smoothing'] / options['num_classes'] + (1 - options['smoothing']) `
The threshold should be a fixed value given the 'smoothing' value and the number of classes.

![image](https://user-images.githubusercontent.com/55440897/203791342-f737f70d-5de4-4291-b728-e942853eb4c3.png)
I am very confused how the thresholds in this table are obtained and in which part of the code they are calculated.

hope to get your reply.

**Comment by wjun0830** [comment]
Thanks for your interest in our work.

If you mean by the thresholds for DIAS (*), we've searched for the best threshold with a cross-validation technique like other methods.

We refer to Sec. 3.4 in the paper.

![image](https://user-images.githubusercontent.com/31557552/203911736-6e1ecd24-189c-480c-ae22-f0b320ffedae.png)


Hope this answers your question.

**Comment by ZhongQiuyuan** [comment]
Thank you for your reply.
What I'm wondering about is the calculation of DIAS and not DIAS(*).
According to the code
`thr = options['smoothing'] / options['num_classes'] + (1 - options['smoothing']) `
In the case of smoothing=0.5 and num_class=6, then thr=0.58333
![image](https://user-images.githubusercontent.com/55440897/203933180-3e7bdf1a-da0d-4e22-874f-5e48675db0a1.png)
I want to know how these thresholds are calculated, I didn't find it in the code.

**Comment by wjun0830** [comment]
Well.. Um.. Sorry but I dont really understand the question.
thr is the calculated threshold itself.

**Comment by ZhongQiuyuan** [comment]
![image](https://user-images.githubusercontent.com/55440897/203938591-e8420a17-6db5-4692-94cc-0ad6a32be70f.png)
The paper says that no extra algorithm is required to calculate the threshold, and the calculation formula of the threshold is given.
![image](https://user-images.githubusercontent.com/55440897/203938859-0c5e0c06-1990-425e-8909-033df6c5231f.png)
But the value calculated by this formula is 0.58333...  It is different from the values given in the tab7.

**Comment by wjun0830** [comment]
For datasets with 6 classes for closed-set, 0.58333... is the right confidence threshold we use for Tab. 7.

**Comment by ZhongQiuyuan** [comment]
I understand what you mean. I misunderstood the content in Table 7. I thought the value in Table 7 was the threshold， now I know it is F1 score?
Thank you for your patient reply.

**Comment by wjun0830** [comment]
Oh! oops sorry for making confusion in Tab. 7.
We didn't notice that readers might be confused with the evaluation metric.
Yes, Tab. 7 is reported with F1-scores.
If you have any further questions, please feel free.
