### ISSUE TITLE
How to set split information when training custom dataset?

### ISSUE THREAD

**Issue by jhgfkdj** [wjun0830/Difficulty-Aware-Simulator#4]
HI i want to train my custom dataset, can you plz tell me how to set split information?
Actually i don't understand the lists in split.py. Why are they that kind of split in cifar or minist.

**Comment by wjun0830** [comment]
Hello. 
Thanks for your interest.

The split information exists to evaluate the OSR performances.
If you are trying to train your custom dataset to launch the model for the application, splitting the dataset may not be necessary unless you want to evaluate the model under specific settings.

Besides, the form of the split in split.py is from the previous works.
For fair comparisons with previous works, we adopted the split information that was used in previous works. (They say they randomly chose the classes for the Closed / Open set.)

You may modify the split.py to evaluate in various open set circumstances.

**Comment by jhgfkdj** [comment]
Thank you, if it randomly chose the classes for  Closed / Open set, then let me try the same way of splitting my custom dataset.
